import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { renderDebugCard } from "../skill/whodunit/scripts/lib/card.js";

const manifest = JSON.parse(fs.readFileSync("package.manifest.json", "utf8"));
const slug = manifest.name.split("/")[1],
  brand = process.argv[2] ?? "Whodunit",
  repo = manifest.repository.url.replace("git+", "").replace(/\.git$/u, "");
const output = path.resolve(".cache/site");
fs.mkdirSync(output, { recursive: true });
// The report is generated by the same offline renderer the skill ships.
fs.rmSync(path.join(output, "example.html"), { force: true });
const report = renderDebugCard(
  JSON.parse(fs.readFileSync("site/example-report.json", "utf8")),
);
const externalIcon =
  '<svg class="dc-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path fill="currentColor" d="M14 3h7v7h-2V6.4l-9.3 9.3-1.4-1.4L17.6 5H14zM5 5h6v2H5v12h12v-6h2v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2z"/></svg>';
const actions = `<section class="dc-actions" aria-label="Fix options"><div class="dc-action-row"><a class="dc-action dc-action-primary" href="https://polylane.com/?utm_source=whodunit&amp;utm_medium=example&amp;utm_content=fix-it" target="_blank" rel="noopener noreferrer">Fix it ${externalIcon}</a><a class="dc-action" href="https://polylane.com/?utm_source=whodunit&amp;utm_medium=example&amp;utm_content=auto-fix" target="_blank" rel="noopener noreferrer">Enable auto-fix ${externalIcon}</a></div></section>`;
if (!report.includes('<footer class="dc-brand"'))
  throw Error("The shared report is missing its footer.");
// Website actions lead to Polylane. Installed reports keep the agent's own fix flow.
const example = report.replace(
  '<footer class="dc-brand"',
  `${actions}<footer class="dc-brand"`,
);
const scripts = [...example.matchAll(/<script>([\s\S]*?)<\/script>/gu)].map(
  (match) =>
    `'sha256-${createHash("sha256").update(match[1]).digest("base64")}'`,
);
const html = fs
  .readFileSync("site/index.template.html", "utf8")
  .replaceAll("__BRAND__", brand)
  .replaceAll("__REPO__", repo)
  .replaceAll("__COMMAND__", process.argv[3] ?? `npx ${manifest.name}`)
  .replaceAll("__SLUG__", slug)
  .replace("__EXAMPLE__", example);
fs.writeFileSync(path.join(output, "index.html"), html);
for (const name of ["style.css", "site.js", "theme-init.js", "favicon.svg"])
  fs.copyFileSync(path.join("site", name), path.join(output, name));
fs.mkdirSync(path.join(output, "assets"), { recursive: true });
for (const name of fs.readdirSync("site/assets"))
  fs.copyFileSync(
    path.join("site/assets", name),
    path.join(output, "assets", name),
  );
const csp = `default-src 'none'; style-src 'self' 'unsafe-inline'; script-src 'self' ${scripts.join(" ")}; font-src 'self' data:; img-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'`;
fs.writeFileSync(
  path.join(output, "_headers"),
  `/*\n  Content-Security-Policy: ${csp}\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  Cache-Control: no-store\n`,
);
console.log(output);
